# Import

In [1]:
import os
import sys
sys.path.append(os.path.join(os.getcwd(),".."))

import time
import math
import json
import glob

import numpy as np
import pandas as pd
import scipy
from scipy.optimize import minimize, least_squares
import matplotlib.pyplot as plt

import cv2
import torch
from torch.nn.functional import mse_loss

import pytorch_kinematics as pk
from urdf_parser_py.urdf import URDF

In [2]:
# Explicitly telling to use GPU
torch.set_default_device('cuda')
torch.set_default_dtype(d=torch.float64)

# Helper Functions

In [3]:
def load_json(filename: str):
    # Construct the absolute path by joining the current directory and relative path
    absolute_path = os.path.join(os.getcwd(), '..', filename)
    # Load the JSON data
    with open(absolute_path, 'r') as file:
        json_data = json.load(file)    
    return json_data

def projectPoints(pts_3d, ext_mtx, cam_mtx, dist_coef):
    # Apply extrinsic transformation (rotation + translation)
    pts_3d_transformed = (ext_mtx @ pts_3d).reshape(-1,4).T
    
    # Convert back from homogeneous to 2D coordinates
    pts_2d_prime = pts_3d_transformed[:2, :] / pts_3d_transformed[2, :]
    x_prime = pts_2d_prime[0]
    y_prime = pts_2d_prime[1]
    
    # Distortion Parameters Calculation
    k1, k2, p1, p2, k3 = dist_coef
    
    r2 = x_prime**2 + y_prime**2
    r4 = r2**2
    r6 = r2*r4
    a1 = 2*x_prime*y_prime
    a2 = r2 + 2*x_prime**2
    a3 = r2 + 2*y_prime**2
    
    # Radial distortion
    radial_distortion = 1 + k1*r2 + k2*r4 + k3*r6
    
    # Tangential distortion
    tangential_distortion_x = p1*a1 + p2*a2
    tangential_distortion_y = p1*a3 + p2*a1
    
    # Apply distortion
    x_double_prime = x_prime*radial_distortion + tangential_distortion_x
    y_double_prime = y_prime* radial_distortion + tangential_distortion_y
    
    # Intrinsic Camera Matrix
    fx = cam_mtx[0,0]
    cx = cam_mtx[0,2]
    fy = cam_mtx[1,1]
    cy = cam_mtx[1,2]
    
    u = x_double_prime*fx + cx
    v = y_double_prime*fy + cy

    return u,v

def xml_to_str(robot):
    # To XML string with filtering
    temp_str = robot.to_xml_string()
    words = temp_str.split()
    words[5] = '>'
    urdf_str = ' '.join(words)
    return urdf_str

def min_max_scaler(tensor, tensor_min, tensor_max):  
    # Apply Min-Max scaling
    scaled_tensor = (tensor - tensor_min) / (tensor_max - tensor_min)
    
    return scaled_tensor

# Initialization

In [4]:
# PyTorch Configs

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float64

In [5]:
# Load Configs
cam_mtxs = load_json('camera_mtx.json')
gaze_ctrs = load_json('calib_params.json')
urdf_path = os.path.join(os.getcwd(),"..","urdf","chest_grace.urdf")
robot = URDF.from_xml_file(urdf_path)

In [6]:
# Load Dataset CSV

data_dir = "final"
csv_file = os.path.join(os.getcwd(),"..","data", data_dir, "240909_grace_dataset.csv")
df = pd.read_csv(csv_file)
temp_df = df.iloc[:,:12]
print('Total:',len(temp_df))
temp_df

Total: 209731


x_c_l     y_c_l     z_c_l     x_c_r     y_c_r     z_c_r   
0      -0.873669 -0.334702  0.738088 -1.166921 -0.352033  0.738508  \
1      -0.821681 -0.331576  0.738000 -0.997318 -0.340332  0.738221   
2      -0.731501 -0.324165  0.738176 -0.868484 -0.332085  0.738360   
3      -0.672994 -0.320809  0.737795 -0.776648 -0.327031  0.737932   
4      -0.613507 -0.317492  0.737656 -0.690487 -0.321762  0.737752   
...          ...       ...       ...       ...       ...       ...   
209726  0.792502 -0.267949  0.950136  0.716083 -0.253872  0.953027   
209727  0.871620 -0.284761  0.947121  0.792232 -0.271009  0.950140   
209728  0.958315 -0.302900  0.943909  0.875639 -0.289312  0.947054   
209729  1.054044 -0.323434  0.940457  0.967562 -0.310196  0.943755   
209730  1.136958 -0.341669  0.937271  1.052510 -0.328020  0.940490   

        cmd_theta_lower_neck_pan  cmd_theta_lower_neck_tilt   
0                            -35                        -10  \
1                            -35                        -10   
2                            -35                        -10   
3                            -35                        -10   
4                            -35                        -10   
...                          ...                        ...   
209726                        35                         30   
209727                        35                         30   
209728                        35                         30   
209729                        35                         30   
209730                        35                         30   

        cmd_theta_upper_neck_tilt  cmd_theta_left_eye_pan   
0                             -10                     -14  \
1                             -10                     -12   
2                             -10                     -10   
3                             -10                      -8   
4                             -10                      -6   
...                           ...                     ...   
209726                         40                       4   
209727                         40                       6   
209728                         40                       8   
209729                         40                      10   
209730                         40                      12   

        cmd_theta_right_eye_pan  cmd_theta_eyes_tilt  
0                           -14                   20  
1                           -12                   20  
2                           -10                   20  
3                            -8                   20  
4                            -6                   20  
...                         ...                  ...  
209726                        4                  -30  
209727                        6                  -30  
209728                        8                  -30  
209729                       10                  -30  
209730                       12                  -30  

[209731 rows x 12 columns]

In [7]:
# Sample 1000
small_df = temp_df.sample(n=100, random_state=1).reset_index(drop=True)

In [8]:
# Convert DF Degrees Column to Radians

data_df = temp_df.copy()
data_df['cmd_theta_lower_neck_pan'] = np.radians(data_df['cmd_theta_lower_neck_pan'].values)
data_df['cmd_theta_lower_neck_tilt'] = np.radians(data_df['cmd_theta_lower_neck_tilt'].values)
data_df['cmd_theta_upper_neck_tilt'] = np.radians(data_df['cmd_theta_upper_neck_tilt'].values)
data_df['cmd_theta_left_eye_pan'] = np.radians(data_df['cmd_theta_left_eye_pan'].values)
data_df['cmd_theta_right_eye_pan'] = np.radians(data_df['cmd_theta_right_eye_pan'].values)
data_df['cmd_theta_eyes_tilt'] = np.radians(data_df['cmd_theta_eyes_tilt'].values)
data_df

x_c_l     y_c_l     z_c_l     x_c_r     y_c_r     z_c_r   
0      -0.873669 -0.334702  0.738088 -1.166921 -0.352033  0.738508  \
1      -0.821681 -0.331576  0.738000 -0.997318 -0.340332  0.738221   
2      -0.731501 -0.324165  0.738176 -0.868484 -0.332085  0.738360   
3      -0.672994 -0.320809  0.737795 -0.776648 -0.327031  0.737932   
4      -0.613507 -0.317492  0.737656 -0.690487 -0.321762  0.737752   
...          ...       ...       ...       ...       ...       ...   
209726  0.792502 -0.267949  0.950136  0.716083 -0.253872  0.953027   
209727  0.871620 -0.284761  0.947121  0.792232 -0.271009  0.950140   
209728  0.958315 -0.302900  0.943909  0.875639 -0.289312  0.947054   
209729  1.054044 -0.323434  0.940457  0.967562 -0.310196  0.943755   
209730  1.136958 -0.341669  0.937271  1.052510 -0.328020  0.940490   

        cmd_theta_lower_neck_pan  cmd_theta_lower_neck_tilt   
0                      -0.610865                  -0.174533  \
1                      -0.610865                  -0.174533   
2                      -0.610865                  -0.174533   
3                      -0.610865                  -0.174533   
4                      -0.610865                  -0.174533   
...                          ...                        ...   
209726                  0.610865                   0.523599   
209727                  0.610865                   0.523599   
209728                  0.610865                   0.523599   
209729                  0.610865                   0.523599   
209730                  0.610865                   0.523599   

        cmd_theta_upper_neck_tilt  cmd_theta_left_eye_pan   
0                       -0.174533               -0.244346  \
1                       -0.174533               -0.209440   
2                       -0.174533               -0.174533   
3                       -0.174533               -0.139626   
4                       -0.174533               -0.104720   
...                           ...                     ...   
209726                   0.698132                0.069813   
209727                   0.698132                0.104720   
209728                   0.698132                0.139626   
209729                   0.698132                0.174533   
209730                   0.698132                0.209440   

        cmd_theta_right_eye_pan  cmd_theta_eyes_tilt  
0                     -0.244346             0.349066  
1                     -0.209440             0.349066  
2                     -0.174533             0.349066  
3                     -0.139626             0.349066  
4                     -0.104720             0.349066  
...                         ...                  ...  
209726                 0.069813            -0.523599  
209727                 0.104720            -0.523599  
209728                 0.139626            -0.523599  
209729                 0.174533            -0.523599  
209730                 0.209440            -0.523599  

[209731 rows x 12 columns]

In [31]:
print(data_df['cmd_theta_lower_neck_tilt'].unique())

[-0.17453293  0.          0.17453293  0.34906585  0.52359878]


In [9]:
# Decision Variables Initial Value

var_dict= {
    'neck_pitch_polyfit_b0': 0.1,
    'neck_pitch_polyfit_b1': 0.1,
    'neck_pitch_polyfit_b2': 0,
    'neck_pitch_polyfit_b3': 0,

    'neck_yaw_polyfit_b0': 0.1,
    'neck_yaw_polyfit_b1': 0.1,
    'neck_yaw_polyfit_b2': 0,
    'neck_yaw_polyfit_b3': 0,

    'head_pitch_polyfit_b0': 0.1,
    'head_pitch_polyfit_b1': 0.1,
    'head_pitch_polyfit_b2': 0,
    'head_pitch_polyfit_b3': 0,

    'eyes_pitch_polyfit_b0': 0.1,
    'eyes_pitch_polyfit_b1': 0.1,
    'eyes_pitch_polyfit_b2': 0,
    'eyes_pitch_polyfit_b3': 0,

    'lefteye_yaw_polyfit_b0': 0.1,
    'lefteye_yaw_polyfit_b1': 0.1,
    'lefteye_yaw_polyfit_b2': 0,
    'lefteye_yaw_polyfit_b3': 0,

    'righteye_yaw_polyfit_b0': 0.1,
    'righteye_yaw_polyfit_b1': 0.1,
    'righteye_yaw_polyfit_b2': 0,
    'righteye_yaw_polyfit_b3': 0,

    'torso_origin_x': -0.12234,
    'torso_origin_y': -0.0325,
    'torso_origin_z': 0.05692,

    'neck_pitch_rot_r': 0,
    
    'head_pitch_origin_z': 0.13172,
    'head_pitch_rot_r': 0,
    'head_pitch_rot_y': 0,

    'eyes_pitch_origin_x': 0.08492,
    'eyes_pitch_origin_z': 0.05186,
    'eyes_pitch_rot_r': 0,
    'eyes_pitch_rot_y': 0,

    'lefteye_yaw_origin_y': 0.02895,
    
    'righteye_yaw_origin_y': -0.02895,

    'lefteye_cam_origin_x': 0.015,
    'lefteye_cam_rot_r': 0,
    'lefteye_cam_rot_p': 0,
    'lefteye_cam_rot_y': 0,

    'righteye_cam_origin_x': 0.015,
    'righteye_cam_rot_r': 0,
    'righteye_cam_rot_p': 0,
    'righteye_cam_rot_y': 0,
}

# Decision Variables 
var_list = list(var_dict.values())

# Variable Names
var_names_list = list(var_dict.keys())

In [10]:
# Index to Name Mapping
var2idx = dict(zip(list(range(len(var_names_list))),var_names_list))
var2idx

{0: 'neck_pitch_polyfit_b0',
 1: 'neck_pitch_polyfit_b1',
 2: 'neck_pitch_polyfit_b2',
 3: 'neck_pitch_polyfit_b3',
 4: 'neck_yaw_polyfit_b0',
 5: 'neck_yaw_polyfit_b1',
 6: 'neck_yaw_polyfit_b2',
 7: 'neck_yaw_polyfit_b3',
 8: 'head_pitch_polyfit_b0',
 9: 'head_pitch_polyfit_b1',
 10: 'head_pitch_polyfit_b2',
 11: 'head_pitch_polyfit_b3',
 12: 'eyes_pitch_polyfit_b0',
 13: 'eyes_pitch_polyfit_b1',
 14: 'eyes_pitch_polyfit_b2',
 15: 'eyes_pitch_polyfit_b3',
 16: 'lefteye_yaw_polyfit_b0',
 17: 'lefteye_yaw_polyfit_b1',
 18: 'lefteye_yaw_polyfit_b2',
 19: 'lefteye_yaw_polyfit_b3',
 20: 'righteye_yaw_polyfit_b0',
 21: 'righteye_yaw_polyfit_b1',
 22: 'righteye_yaw_polyfit_b2',
 23: 'righteye_yaw_polyfit_b3',
 24: 'torso_origin_x',
 25: 'torso_origin_y',
 26: 'torso_origin_z',
 27: 'neck_pitch_rot_r',
 28: 'head_pitch_origin_z',
 29: 'head_pitch_rot_r',
 30: 'head_pitch_rot_y',
 31: 'eyes_pitch_origin_x',
 32: 'eyes_pitch_origin_z',
 33: 'eyes_pitch_rot_r',
 34: 'eyes_pitch_rot_y',
 35: 'le

In [11]:
# Tensor Initialization

# Chest Camera OpenCV to World Orientation (LHR > RHR)
T_opencv_world = torch.Tensor([[0.0, 0.0, 1.0, 0.0],
                               [-1.0, 0.0, 0.0, 0.0],
                               [0.0, -1.0, 0.0, 0.0],
                               [0.0, 0.0, 0.0, 1.0]]).to(dtype=dtype, device=device)

# World Orientation to Chest Camera OpenCV (RHR > LHR)
T_world_opencv = torch.Tensor([[0.0, -1.0, 0.0, 0.0],
                               [0.0, 0.0, -1.0, 0.0],
                               [1.0, 0.0, 0.0, 0.0],
                               [0.0, 0.0, 0.0, 1.0]]).to(dtype=dtype, device=device)

### Camera Projection
# Camera Parameters
left_cam_mtx = torch.Tensor(cam_mtxs['left_eye']['camera_matrix'])
left_dist_coef = torch.Tensor(cam_mtxs['left_eye']['distortion_coefficients']).squeeze()
right_cam_mtx = torch.Tensor(cam_mtxs['right_eye']['camera_matrix'])
right_dist_coef = torch.Tensor(cam_mtxs['right_eye']['distortion_coefficients']).squeeze()

# Loss Function

In [12]:
def objective_function(V, x_c_l, y_c_l, z_c_l, x_c_r, y_c_r, z_c_r,
                      cmd_lnt, cmd_lnp, cmd_unt, cmd_et, cmd_lep, cmd_rep):

    # Convert to Tensor
    x_c_l = torch.Tensor(x_c_l).reshape(-1,1).to(dtype=dtype, device=device)
    y_c_l = torch.Tensor(y_c_l).reshape(-1,1).to(dtype=dtype, device=device)
    z_c_l = torch.Tensor(z_c_l).reshape(-1,1).to(dtype=dtype, device=device)
    x_c_r = torch.Tensor(x_c_r).reshape(-1,1).to(dtype=dtype, device=device)
    y_c_r = torch.Tensor(y_c_r).reshape(-1,1).to(dtype=dtype, device=device)
    z_c_r = torch.Tensor(z_c_r).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_lnt = torch.Tensor(cmd_lnt).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_lnp = torch.Tensor(cmd_lnp).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_unt = torch.Tensor(cmd_unt).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_et = torch.Tensor(cmd_et).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_lep = torch.Tensor(cmd_lep).reshape(-1,1).to(dtype=dtype, device=device)
    cmd_rep = torch.Tensor(cmd_rep).reshape(-1,1).to(dtype=dtype, device=device)
    
    #Joint-to-Motor Polynomial Models
    neck_pitch = (torch.cat((torch.ones(cmd_lnt.shape[0], 1), cmd_lnt, cmd_lnt.pow(2), cmd_lnt.pow(3)), dim=1) @ torch.Tensor([[V[0]],[V[1]],[V[2]],[V[3]]]).to(dtype=dtype, device=device))
    neck_yaw = (torch.cat((torch.ones(cmd_lnp.shape[0], 1), cmd_lnp, cmd_lnp.pow(2), cmd_lnp.pow(3)), dim=1) @ torch.Tensor([[V[4]],[V[5]],[V[6]],[V[7]]]).to(dtype=dtype, device=device))
    head_pitch = (torch.cat((torch.ones(cmd_unt.shape[0], 1), cmd_unt, cmd_unt.pow(2), cmd_unt.pow(3)), dim=1) @ torch.Tensor([[V[8]],[V[9]],[V[10]],[V[11]]]).to(dtype=dtype, device=device))
    eyes_pitch = (torch.cat((torch.ones(cmd_et.shape[0], 1), cmd_et, cmd_et.pow(2), cmd_et.pow(3)), dim=1) @ torch.Tensor([[V[12]],[V[13]],[V[14]],[V[15]]]).to(dtype=dtype, device=device))
    lefteye_yaw = (torch.cat((torch.ones(cmd_lep.shape[0], 1), cmd_lep, cmd_lep.pow(2), cmd_lep.pow(3)), dim=1) @ torch.Tensor([[V[16]],[V[17]],[V[18]],[V[19]]]).to(dtype=dtype, device=device))
    righteye_yaw = (torch.cat((torch.ones(cmd_rep.shape[0], 1), cmd_rep, cmd_rep.pow(2), cmd_rep.pow(3)), dim=1) @ torch.Tensor([[V[20]],[V[21]],[V[22]],[V[23]]]).to(dtype=dtype, device=device))

    # URDF Variable Assignment
    for joint in robot.joints:
        # if joint.name == 'torso':
        #     joint.origin.position[0] = V[24]
        #     joint.origin.position[1] = V[25]
        #     joint.origin.position[2] = V[26]
        if joint.name == 'neck_pitch':
            joint.origin.rotation[0] = V[27]
        # elif joint.name == 'neck_pitch':
        #     joint.origin.rotation[0] = V[27]
        # elif joint.name == 'head_pitch':
            # joint.origin.position[2] = V[28]
            # joint.origin.rotation[0] = V[29]
            # joint.origin.rotation[2] = V[30]
        # elif joint.name == 'eyes_pitch':
        #     joint.origin.position[0] = V[31]
            # joint.origin.position[2] = V[32]
            # joint.origin.rotation[0] = V[33]
            # joint.origin.rotation[2] = V[34]
        # elif joint.name == 'lefteye_yaw':
        #     # oint.origin.position[1] = V[35]
        # elif joint.name == 'righteye_yaw':
        #     # joint.origin.position[1] = V[36]
        elif joint.name == 'lefteye_cam':
            # joint.origin.position[0] = V[37]
            joint.origin.rotation[0] = V[38]
            joint.origin.rotation[1] = V[39]
            joint.origin.rotation[2] = V[40]
        elif joint.name == 'righteye_cam':
            # joint.origin.position[0] = V[41]
            joint.origin.rotation[0] = V[42]
            joint.origin.rotation[1] = V[43]
            joint.origin.rotation[2] = V[44]
    
    # XML to String
    urdf_str = xml_to_str(robot)
    
    # Kinematic Chain
    chain = pk.build_chain_from_urdf(urdf_str)
    chain.to(dtype=dtype, device=device)
    
    # Specifying Joint Angles (radians)
    joint_cmd = torch.cat((neck_pitch, neck_yaw, head_pitch, eyes_pitch, lefteye_yaw, righteye_yaw), dim=1)
    
    # Forward Kinematics
    ret = chain.forward_kinematics(joint_cmd)
    
    # Realsense to Left Eye Camera (Pytorch) with Points
    T_clprime = torch.linalg.inv(ret['realsense'].get_matrix()) @ ret['leftcamera'].get_matrix()
    
    # Realsense to Right Eye Camera (Pytorch) with Points
    T_crprime = torch.linalg.inv(ret['realsense'].get_matrix()) @ ret['rightcamera'].get_matrix()
    
    # Extrinsic Matrix
    T_left_ext = T_world_opencv @ T_clprime @ T_opencv_world
    T_right_ext = T_world_opencv @ T_crprime @ T_opencv_world
    
    
    # Chest Camera OpenCV Orientation 3D Projection Points
    left_chest_pts = torch.cat((x_c_l, y_c_l, z_c_l,torch.ones(x_c_l.shape[0], 1)), dim=1).reshape(-1,4,1)
    right_chest_pts = torch.cat((x_c_r, y_c_r, z_c_r,torch.ones(x_c_r.shape[0], 1)), dim=1).reshape(-1,4,1)
    
    # Points Projection
    u_left, v_left = projectPoints(left_chest_pts, T_left_ext, left_cam_mtx, left_dist_coef)   
    u_right, v_right = projectPoints(right_chest_pts, T_right_ext, right_cam_mtx, right_dist_coef)

    # Clamping
    u_min_val = 0
    u_max_val = 639 
    v_min_val = 0
    v_max_val = 479
    u_left = torch.clamp(u_left, min=u_min_val, max=u_max_val)
    v_left = torch.clamp(v_left, min=v_min_val, max=v_max_val)
    u_right = torch.clamp(u_right, min=u_min_val, max=u_max_val)
    v_right = torch.clamp(v_right, min=v_min_val, max=v_max_val)
    
    # # Scaling
    u_left = min_max_scaler(u_left, u_min_val, u_max_val)
    v_left = min_max_scaler(v_left, v_min_val, v_max_val)
    u_right = min_max_scaler(u_right, u_min_val, u_max_val)
    v_right = min_max_scaler(v_right, v_min_val, v_max_val)
    
    # True Value
    true_u_left = gaze_ctrs['left_eye']['x_center']
    true_v_left = gaze_ctrs['left_eye']['y_center']
    true_u_right = gaze_ctrs['right_eye']['x_center']
    true_v_right = gaze_ctrs['right_eye']['y_center']
    true_u_left = min_max_scaler(gaze_ctrs['left_eye']['x_center'], u_min_val, u_max_val)
    true_v_left = min_max_scaler(gaze_ctrs['left_eye']['y_center'], v_min_val, v_max_val)
    true_u_right = min_max_scaler(gaze_ctrs['right_eye']['x_center'], u_min_val, u_max_val)
    true_v_right = min_max_scaler(gaze_ctrs['right_eye']['y_center'], v_min_val, v_max_val)

    
    # Loss
    residuals = torch.cat((((u_left-true_u_left)**2).reshape(-1,1),((v_left-true_v_left)**2).reshape(-1,1),((u_right-true_u_right)**2).reshape(-1,1),((v_right-true_v_right)**2).reshape(-1,1)), dim=1).cpu().numpy()
    res_sum = np.sum(residuals, axis=1)

    # Return Loss
    return res_sum

In [13]:
# Input

# Input
V = np.array(var_list)
x_c_l = data_df['x_c_l'].to_numpy()
y_c_l = data_df['y_c_l'].to_numpy()
z_c_l = data_df['z_c_l'].to_numpy()
x_c_r = data_df['x_c_r'].to_numpy()
y_c_r = data_df['y_c_r'].to_numpy()
z_c_r = data_df['z_c_r'].to_numpy()
cmd_lnt = data_df['cmd_theta_lower_neck_tilt'].to_numpy()
cmd_lnp = data_df['cmd_theta_lower_neck_pan'].to_numpy()
cmd_unt = data_df['cmd_theta_upper_neck_tilt'].to_numpy()
cmd_et = data_df['cmd_theta_eyes_tilt'].to_numpy()
cmd_lep = data_df['cmd_theta_left_eye_pan'].to_numpy()
cmd_rep = data_df['cmd_theta_right_eye_pan'].to_numpy()

In [14]:
# Test Objective Function
objective_function(V, x_c_l, y_c_l, z_c_l, x_c_r, y_c_r, z_c_r,
                      cmd_lnt, cmd_lnp, cmd_unt, cmd_et, cmd_lep, cmd_rep)

array([0.97398521, 0.97398521, 0.97398521, ..., 1.21498678, 1.21498678,
       1.21498678])

# Least Squares

In [15]:
opt = least_squares(objective_function, V, verbose=2, max_nfev=200, args=(x_c_l, y_c_l, z_c_l, x_c_r, y_c_r, z_c_r,
                                                 cmd_lnt, cmd_lnp, cmd_unt, cmd_et, cmd_lep, cmd_rep))
opt

   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality   
       0              1         1.0963e+05                                    1.12e+05    
       1              2         7.5679e+04      3.40e+04       4.11e-01       1.55e+05    
       2              3         3.6461e+04      3.92e+04       8.21e-01       1.38e+05    
       3              5         2.7771e+04      8.69e+03       4.11e-01       3.55e+04    
       4              6         1.7702e+04      1.01e+04       4.11e-01       2.26e+04    
       5              7         1.1104e+04      6.60e+03       8.21e-01       3.53e+04    
       6              8         5.6634e+03      5.44e+03       8.21e-01       2.80e+04    
       7              9         2.0119e+03      3.65e+03       8.21e-01       1.27e+04    
       8             11         1.3708e+03      6.41e+02       4.11e-01       1.15e+04    
       9             14         1.2732e+03      9.76e+01       2.57e-02       7.20e+03    

     message: The maximum number of function evaluations is exceeded.
     success: False
      status: 0
         fun: [ 2.573e-01  2.284e-01 ...  5.759e-02  5.800e-02]
           x: [-1.263e+00  2.823e-01 ... -2.849e-01  2.733e-01]
        cost: 996.8327110390535
         jac: [[-1.376e+00  2.401e-01 ... -0.000e+00  0.000e+00]
               [-1.268e+00  2.213e-01 ... -0.000e+00  0.000e+00]
               ...
               [ 6.415e-02  3.359e-02 ... -0.000e+00  0.000e+00]
               [ 6.056e-02  3.171e-02 ... -0.000e+00  0.000e+00]]
        grad: [ 4.450e+01  1.248e+01 ...  0.000e+00  0.000e+00]
  optimality: 469.74317249532055
 active_mask: [ 0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
        nfev: 200
        njev: 192

In [16]:
opt.grad

array([ 4.44984469e+01,  1.24844233e+01, -7.60130657e+00, -3.02561025e+00,
       -4.71844634e+01,  6.61909700e+01, -7.49589248e+00, -1.92142848e+01,
       -4.34648576e+01,  2.17545999e+01, -2.48562719e+01, -1.89463368e+01,
        3.79733484e+01,  4.55649713e-01,  3.57358101e+00, -4.17876148e+00,
       -3.71857176e+01,  1.52573125e+02,  4.40150135e+00,  5.76054555e+00,
       -3.20929390e+01,  1.49177388e+02, -8.69200984e+00,  6.21638284e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -4.69743172e+02,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00])

In [17]:
dict(zip(var_names_list, opt.grad))

{'neck_pitch_polyfit_b0': 44.49844693779907,
 'neck_pitch_polyfit_b1': 12.484423284926548,
 'neck_pitch_polyfit_b2': -7.6013065674899405,
 'neck_pitch_polyfit_b3': -3.0256102471395687,
 'neck_yaw_polyfit_b0': -47.18446339314099,
 'neck_yaw_polyfit_b1': 66.19096997669098,
 'neck_yaw_polyfit_b2': -7.495892484490739,
 'neck_yaw_polyfit_b3': -19.21428480667107,
 'head_pitch_polyfit_b0': -43.46485757476597,
 'head_pitch_polyfit_b1': 21.75459993374568,
 'head_pitch_polyfit_b2': -24.856271905858705,
 'head_pitch_polyfit_b3': -18.946336833180904,
 'eyes_pitch_polyfit_b0': 37.97334837031957,
 'eyes_pitch_polyfit_b1': 0.45564971310055835,
 'eyes_pitch_polyfit_b2': 3.573581006979369,
 'eyes_pitch_polyfit_b3': -4.178761475608189,
 'lefteye_yaw_polyfit_b0': -37.18571755872221,
 'lefteye_yaw_polyfit_b1': 152.57312483493735,
 'lefteye_yaw_polyfit_b2': 4.401501349099382,
 'lefteye_yaw_polyfit_b3': 5.760545545315666,
 'righteye_yaw_polyfit_b0': -32.09293900894279,
 'righteye_yaw_polyfit_b1': 149.177387

In [18]:
dict(zip(var_names_list, opt.x))

{'neck_pitch_polyfit_b0': -1.2630789221912768,
 'neck_pitch_polyfit_b1': 0.2822730388854533,
 'neck_pitch_polyfit_b2': -0.015200329945517413,
 'neck_pitch_polyfit_b3': 0.007570994341067157,
 'neck_yaw_polyfit_b0': -0.21510449569401918,
 'neck_yaw_polyfit_b1': -1.6371674798645992,
 'neck_yaw_polyfit_b2': 0.021750270963396826,
 'neck_yaw_polyfit_b3': -0.24205737557278717,
 'head_pitch_polyfit_b0': 0.21603816033597692,
 'head_pitch_polyfit_b1': -0.4637435934339799,
 'head_pitch_polyfit_b2': 0.01770784687234988,
 'head_pitch_polyfit_b3': 0.044101989093107995,
 'eyes_pitch_polyfit_b0': 0.5327811660447581,
 'eyes_pitch_polyfit_b1': -0.28494145956693157,
 'eyes_pitch_polyfit_b2': 0.07362009655765223,
 'eyes_pitch_polyfit_b3': -0.03368459739666263,
 'lefteye_yaw_polyfit_b0': -0.16122341871802073,
 'lefteye_yaw_polyfit_b1': -1.3322582618869745,
 'lefteye_yaw_polyfit_b2': -0.09311555357613016,
 'lefteye_yaw_polyfit_b3': -0.05432233809830462,
 'righteye_yaw_polyfit_b0': -0.019594909391744766,
 'r

In [19]:
# URDF
W = opt.x

In [20]:
for joint in robot.joints:
    if joint.name == 'torso':
        joint.origin.position[0] = W[24]
        joint.origin.position[1] = W[25]
        joint.origin.position[2] = W[26]
    elif joint.name == 'neck_pitch':
        joint.origin.rotation[0] = W[27]
    elif joint.name == 'head_pitch':
        joint.origin.position[2] = W[28]
        joint.origin.rotation[0] = W[29]
        joint.origin.rotation[2] = W[30]
    elif joint.name == 'eyes_pitch':
        joint.origin.position[0] = W[31]
        joint.origin.position[2] = W[32]
        joint.origin.rotation[0] = W[33]
        joint.origin.rotation[2] = W[34]
    elif joint.name == 'lefteye_yaw':
        joint.origin.position[1] = W[35]
    elif joint.name == 'righteye_yaw':
        joint.origin.position[1] = W[36]
    elif joint.name == 'lefteye_cam':
        joint.origin.position[0] = W[37]
        joint.origin.rotation[0] = W[38]
        joint.origin.rotation[1] = W[39]
        joint.origin.rotation[2] = W[40]
    elif joint.name == 'righteye_cam':
        joint.origin.position[0] = W[41]
        joint.origin.rotation[0] = W[42]
        joint.origin.rotation[1] = W[43]
        joint.origin.rotation[2] = W[44]

In [26]:
urdf_path = os.path.join(os.getcwd(), '..','urdf', 'chest_grace_results.urdf')

In [27]:
results_str = robot.to_xml_string()
print(results_str)

<?xml version="1.0" ?>
<robot name="robot" version="1.0">
  <link name="world"/>
  <link name="torso">
    <visual>
      <origin xyz="0.01767 0.0 -0.267155" rpy="-1.3064604870132741e-16 0 -5.643848308639651e-17"/>
      <geometry>
        <box size="0.26 0.3 0.6"/>
      </geometry>
      <material name="robot_model">
        <color rgba="0.3 0.3 0.3 0.4"/>
      </material>
    </visual>
  </link>
  <link name="realsense">
    <visual>
      <origin xyz="-0.01485 -0.0325 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.025 0.09 0.025"/>
      </geometry>
      <material name="robot_camera">
        <color rgba="0.0 0.1 0.3 0.6"/>
      </material>
    </visual>
  </link>
  <link name="neck">
    <visual>
      <origin xyz="0.0 0.0 0.07" rpy="-1.3064604870132741e-16 0 -5.643848308639651e-17"/>
      <geometry>
        <cylinder radius="0.045" length="0.14"/>
      </geometry>
      <material name="robot_model">
        <color rgba="0.3 0.3 0.3 0.4"/>
      </material>
  

In [28]:
# Write the XML string to a .urdf file
with open(urdf_path, 'w') as file:
    file.write(results_str)

print(f"XML string saved to {urdf_path}")

XML string saved to /home/jaynieles/dev/grace_dl/notebooks/../urdf/chest_grace_results.urdf


In [29]:
urdf_path

'/home/jaynieles/dev/grace_dl/notebooks/../urdf/chest_grace_results.urdf'

In [37]:
cmd_lnt = torch.Tensor([-0.17453293]).to(dtype=dtype, device=device).reshape(-1,1)
V = W
neck_pitch = (torch.cat((torch.ones(cmd_lnt.shape[0], 1), cmd_lnt, cmd_lnt.pow(2), cmd_lnt.pow(3)), dim=1) @ torch.Tensor([[V[0]],[V[1]],[V[2]],[V[3]]]).to(dtype=dtype, device=device))
neck_pitch

tensor([[-1.3128]], device='cuda:0')